---
title: "C6 Trial"
author: "Ruochen Liu rl2841"
date: "April 5, 2017"
output: html_document
---

```{r}
#### Get M Matrix for each dataset
#K <- length(data_list)
#M <- data_list
#for(i in 1:K){
#  M[[i]] <- M6(data_list[[i]])
#  cat(i, " Completed ", K-i, " Left", sep = "")
#}
#M.Matrix <- M
#names(M.Matrix) <- names(data_list)
#save(M.Matrix, file = "../output/M.RData")

```

```{r}
require("pacman")
pacman::p_load(text2vec, dplyr, qlcMatrix, kernlab, knitr)
source("../lib/M.R")
load("../output/CleanData.RData")
load("../output/M.RData")
source("../lib/C6_train.R")
source('../lib/evaluation_measures.R')
#### Get Features

d <- data_list[[10]]
M <- M.Matrix[[10]]
n <- length(d) #### Number of publications
paper <- vector("character", length = n)
for(i in 1:n){
  paper[i] <- d[[i]][[5]]
}

it_train <- itoken(paper, 
             preprocessor = tolower, 
             tokenizer = word_tokenizer,
             progressbar = FALSE)
vocab <- create_vocabulary(it_train, stopwords = c("a", "an", "the", "in", "on",
                                                   "at", "of", "above", "under"))
vectorizer <- vocab_vectorizer(vocab)
dtm_train <- create_dtm(it_train, vectorizer)
dim(dtm_train)
tfidf <- TfIdf$new()
train.data <- as.matrix(fit_transform(dtm_train, tfidf)) #### Get train data features.
data.train <- train.data
t <- 3
label <- vector("numeric", length = n) #### Save true assignments.
for(i in 1:n){
  label[i] <- d[[i]][[1]]
}
k <- length(unique(label)) #### Number of clusters.

#### Train
train_label <- Train(train.data, M, k, t)
#### Result
matching_matrix_c6 <- matching_matrix(label,train_label)
performance_c6 <- performance_statistics(matching_matrix_c6)


```